### ISSUE TITLE
Correlation in simple x**2

### ISSUE THREAD

**Issue by APN-Pucky** [tisimst/mcerp#24]
I am comparing some error propagation libraries.

In the following example the gauss distributed points squared are shifted by ~1 standard deviation due to them being the same/correlated and have a final standard deviation of `0.14119022393747466 ~ sqrt(2)*0.1`:

```python
>>> mcerp.N(1e-6,0.1**0.5)**2
uv(0.09997863287775294, 0.01993467933551424, 2.7882026688307877, 14.26098019729975)
>>> mcerp.N(1e-6,0.1**0.5)*mcerp.N(1e-6,0.1**0.5)
uv(-8.630502073240223e-05, 0.010000311411364413, -0.007846160948921321, 9.143864353123542)
```

Other derivative based uncertainty libraries (jacobi, uncertainties) give `1.e-12 +- 6.e-7` for the square.

```python
>>> uncertainties.ufloat(1e-6,0.1**0.5)**2
1e-12+/-6.324555320336758e-07
```

Is this an effect of the other libraries being only first order, since using `x_std/x << 1` gives reasonable agreement?
If I just wanted to compute `x**2` what result is correct for the Monte Carlo method? 
Do I need to use `x_sq=z*y` with separate distributions via `z=N(x,x_std)` and `y=N(x,x_std)`?
Does the same apply to other operators `(+,-,*,/)`?

Cheers APN

**Comment by tisimst** [comment]
Hi, Alexander!

You guessed right. It’s the assumed order that is causing the discrepancy.
It also depends on how nonlinear the function is around the points. If the
function is close to linear, then the first-order models will be close. The
beauty of the Monte Carlo method, and the motivation for me in the first
place, is that it makes no assumptions or simplifications about what order
of function is being calculated; the others do and they work really well
for many applications where a first order model makes sense. So, the MC
method can do a much better job at estimating the actual mean, standard
deviation, etc., in all scenarios, given a sufficiently large sample. Since
the function x**2 is most nonlinear around x=0, it should be no surprise
that they don’t quite give the right answer.

The other thing to recognize is x**2 =/= x*z even if they have the same
mean and standard deviation, especially if x and z are uncorrelated in any
way. They would literally need yield identical samples every time (i.e.,
perfectly correlated) in order for that relation to be true. This just
doesn’t happen in normal random sampling. So, the equation you are looking
for really is just x**2.

**Comment by APN-Pucky** [comment]
Thank you for the quick and clear answer!
